version: '3.8'

networks:
  # Specify the network for bridging
  10kswap-network:
    driver: bridge

services:
  devnet:
    image: shardlabs/starknet-devnet:0.2.11
    ports:
      - '5050:5050'
    networks:
      - 10kswap-network